test: fix

diff --git a/test/bash/UNX/modules_01 b/test/bash/UNX/modules_01
--- a/test/bash/UNX/modules_01
+++ b/test/bash/UNX/modules_01
@@ -4,13 +4,16 @@
 # Prepare Test
 #
 
-if [[ "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" != 'ON' ]]; then
-  echo 'error: Test must be executed inside a container'
-  exit 1
-fi
-if [[ "$DEV_TEST_BASH_RUNNER_ENVIRONMENT" != 'ON' ]]; then
-  echo 'error: Test must be executed inside a CICD runner'
-  exit 1
+if [[ "$(uname -s)" == 'Linux' ]]; then
+  if [[ "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" != 'ON' ]]; then
+    echo 'error: Test must be executed inside a container'
+    exit 1
+  fi
+else
+  if [[ "$DEV_TEST_BASH_RUNNER_ENVIRONMENT" != 'ON' ]]; then
+    echo 'error: Test must be executed inside a CICD runner'
+    exit 1
+  fi
 fi
 
 install_target='/tmp/devbin64'
