rel: promote 7.3.0 (#45)

diff --git a/test/bash/UNX/modules_01 b/test/bash/UNX/modules_01
--- a/test/bash/UNX/modules_01
+++ b/test/bash/UNX/modules_01
@@ -8,6 +8,10 @@ if [[ "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" != 'ON' ]]; then
   echo 'error: Test must be executed inside a container'
   exit 1
 fi
+if [[ "$DEV_TEST_BASH_RUNNER_ENVIRONMENT" != 'ON' ]]; then
+  echo 'error: Test must be executed inside a CICD runner'
+  exit 1
+fi
 
 install_target='/tmp/devbin64'
 test_target="${HOME}/repo"
