refact: normalize lib-base, update templates

diff --git a/src/lib/devbin64/bin/dev-bootstrap b/src/lib/devbin64/bin/dev-bootstrap
--- a/src/lib/devbin64/bin/dev-bootstrap
+++ b/src/lib/devbin64/bin/dev-bootstrap
@@ -35,7 +35,7 @@
 #
 
 # DevBin64 / Current version
-declare DEV_BOOTSTRAP_VERSION='4.3.0'
+declare DEV_BOOTSTRAP_VERSION='5.0.0'
 # DevBin64 / List of optional modules for adding after bootstrap is complete
 declare DEV_BOOTSTRAP_MODULES="${DEV_BOOTSTRAP_MODULES:-}"
 # DevBin64 / Module Library location
@@ -82,6 +82,8 @@ DEV_BOOTSTRAP_FILES+=" ${DEV_BOOTSTRAP_PATH_LIB}/installer64/bin/dev-env-install
 DEV_BOOTSTRAP_FILES+=" ${DEV_BOOTSTRAP_PATH_LIB}/installer64/bin/dev-lib-installer64"
 DEV_BOOTSTRAP_FILES+=" ${DEV_BOOTSTRAP_PATH_LIB}/bashlib64/bin/dev-env-bashlib64"
 DEV_BOOTSTRAP_FILES+=" ${DEV_BOOTSTRAP_PATH_LIB}/bashlib64/bin/dev-lib-bashlib64"
+DEV_BOOTSTRAP_FILES+=" ${DEV_BOOTSTRAP_PATH_LIB}/sysop64/bin/dev-env-sysop64"
+DEV_BOOTSTRAP_FILES+=" ${DEV_BOOTSTRAP_PATH_LIB}/sysop64/bin/dev-lib-sysop64"
 
 # Installer64 / Parameters
 export INST64_BASHLIB64_TARGET=''
@@ -179,7 +181,8 @@ function dev_bootstrap_dot_env_create() {
 # * Used by DevBin64 to define project wide variables
 # * Automatically loaded by dev-set
 # * Do not include local variables (workstation specific) and secrets. Use .local.env and .secrets.env instead
-# * Version: 4.2.0
+# * Version: 1.0.0
+# * Template: 4.2.0
 #
 
 # Main / Base file and directory names
@@ -268,21 +271,31 @@ function dev_bootstrap_lib_base_create() {
   [[ -r "$dev_base" ]] &&
     echo 'Warning: file already create, no further action will be taken' 2>&1 &&
     return 0
-  # shellcheck disable=SC2016
+  # shellcheck disable=SC2016,SC2059
   printf "#!/usr/bin/env bash
 #
 # Dev / Lib / Base / Install base dev-time tools
 #
-# * Use to download or install external tools, libraries, etc
+# * Use to download DevBin64 components in ephemeral environments
 # * Tools and libs should go to lib/
-# * Customize as needed
-# * Template: 1.1.1
+# * For project specific tools, use dev-lib-project
+# * Version: 2.0.0
 #
 
 # shellcheck source=bin/dev-set
 source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 
-./bin/dev-lib-installer64
+# Download main components
+./bin/dev-lib-installer64 &&
+  ./bin/dev-lib-sysop64 ||
+  exit $?
+
+# Download project related components
+if [[ -f ./bin/dev-lib-project ]]; then
+  ./bin/dev-lib-project
+else
+  exit 0
+fi
 " \
     >"$dev_base" &&
     chmod "$DEV_BOOTSTRAP_EXE_MODE" "$dev_base"
@@ -298,7 +311,7 @@ function dev_bootstrap_dot_local_create() {
   fi
 
   # shellcheck disable=SC2016
-  printf '** ACTION REQUIRED: this is a template file. Copy to .local and remove this line **
+  printf '# ** ACTION REQUIRED: this is a template file. Copy to .local.env and remove this line **
 #!/usr/bin/env bash
 #
 # Development environment / Local variables
@@ -307,7 +320,8 @@ function dev_bootstrap_dot_local_create() {
 # * Automatically loaded by dev-set on non CICD environments
 # * For CICD environments, create variables and values based on this file
 # * Source before .env
-# * Version: 3.0.0
+# * Version: 1.0.0
+# * Template: 3.0.1
 #
 
 # Main / Debug flag for bin/ scripts
@@ -327,7 +341,7 @@ function dev_bootstrap_dot_secrets_create() {
     echo 'Warning: file already create, no further action will be taken' 2>&1 &&
     return 0
   # shellcheck disable=SC2016
-  printf '# ** ACTION REQUIRED: this is a template file. Copy to .secrets and remove this line **
+  printf '# ** ACTION REQUIRED: this is a template file. Copy to .secrets.env and remove this line **
 #!/usr/bin/env bash
 #
 # Development environment / Secrets
@@ -335,7 +349,8 @@ function dev_bootstrap_dot_secrets_create() {
 # * This file must be excluded from GIT
 # * Automatically loaded by dev-set on non CICD environments
 # * For CICD environments, create variables and values based on this file
-# * Version: 2.0.0
+# * Version: 1.0.0
+# * Template: 2.0.1
 #
 ' \
     >"$DEV_BASE_DOT_SECRETS" &&
@@ -368,7 +383,8 @@ function dev_bootstrap_gitignore_create() {
   printf '#
 # GIT Ignore
 #
-# * Template version: 2.0.0
+# * Version: 1.0.0
+# * Template: 2.0.1
 #
 
 #
@@ -380,6 +396,7 @@ function dev_bootstrap_gitignore_create() {
 /logs/*
 /tmp/*
 /vault/*
+/.vscode
 
 /%s
 /%s
@@ -387,8 +404,6 @@ function dev_bootstrap_gitignore_create() {
 #
 # Project specific exclusions
 #
-
-/.vscode
 
 # Keep placeholder for empty directories
 !/**/%s
