feat: update modules (#33)

diff --git a/docs/skeletons/dev-lib-base/bin/dev-lib-MODULE b/docs/skeletons/dev-lib-base/bin/dev-lib-MODULE
--- a/docs/skeletons/dev-lib-base/bin/dev-lib-MODULE
+++ b/docs/skeletons/dev-lib-base/bin/dev-lib-MODULE
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #######################################
-# Dev / Env / X_MODULE_TITLE_X / Shared environment variables
+# Dev / Lib / X_MODULE_TITLE_X / Download
 #
 # * Version: 1.0.0
 # * Template: 1.0.1
@@ -22,33 +22,38 @@
 #######################################
 
 #
-# Globals
-#
-# * Use .env file to override values
+# Imports
 #
 
-# shellcheck disable=SC2154
-{
-  # Lib / X_MODULE_TITLE_X / Installer
-  export DEV_LIB_X_MODULE_UPPER_X_INSTALLER="${DEV_LIB_INSTALLER64_TARGET}/install-X_INSTALLER_X"
-  # Lib / X_MODULE_TITLE_X / Target
-  export DEV_LIB_X_MODULE_UPPER_X_TARGET="${DEV_LIB_X_MODULE_UPPER_X_TARGET:-${DEV_PATH_LIB}/X_DESTINATION_X}"
+# shellcheck source=bin/dev-set
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-X_MODULE_X || exit 1
+# shellcheck source-path=lib/bl64
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Functions
+#
+
+function dev_lib_download() {
+  bl64_dbg_app_show_function
+  # X_DOWNLOAD_PLACEHOLDER_X
+}
+
+function dev_lib_initialize() {
+  bl64_dbg_app_show_function
+  # X_INIT_PLACEHOLDER_X
 }
 
 #
-# Locals
-#
-# * Use .local.env file or CICD variables to override values
+# Main
 #
 
-# shellcheck disable=SC2154
-{
-  # Lib / X_MODULE_TITLE_X / Command
-  export DEV_LIB_X_MODULE_UPPER_X_BIN="${DEV_LIB_X_MODULE_UPPER_X_BIN:-${DEV_LIB_X_MODULE_UPPER_X_TARGET}/X_COMMAND_X}"
-}
+[[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
 
-#
-# Secrets
-#
-# * Use .secrets.env file or CICD secrets to override values
-#
+bl64_msg_all_enable_verbose
+bl64_msg_show_batch_start 'dev-lib-X_MODULE_X'
+dev_lib_initialize &&
+  dev_lib_download
+bl64_msg_show_batch_finish $? 'dev-lib-X_MODULE_X'
