feat: add base install

diff --git a/src/devbin64/bin/dev-bootstrap b/src/devbin64/bin/dev-bootstrap
--- a/src/devbin64/bin/dev-bootstrap
+++ b/src/devbin64/bin/dev-bootstrap
@@ -10,7 +10,7 @@
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.3.1
+# Version: 1.4.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -32,9 +32,6 @@
 # Globals
 #
 
-declare DEV_BOOTSTRAP_INSTALLER64_NAME='inst64'
-declare DEV_BOOTSTRAP_BASHLIB64_NAME='bl64'
-
 # Env / Initial values
 declare DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
 declare DEV_LIB_BASHLIB64_TARGET=''
@@ -42,19 +39,77 @@ declare DEV_LIB_INSTALLER64_TARGET=''
 declare DEV_LIB_INSTALLER64_OWNER='automation64/installer64'
 declare DEV_PATH_ROOT=''
 declare DEV_PATH_LIB=''
-declare DEV_PATHS_MODE='0755'
-declare DEV_PATHS='bin build docs lib src test tmp var'
 declare DEV_BASE_DOT_LOCAL='dot.local'
 declare DEV_BASE_DOT_SECRETS='dot.secrets'
 declare DEV_BASE_ENV='.env'
 
 # Installer64 / Parameters
-export INST64_INSTALLER64_TARGET=''
+export DEV_PATH_BIN=''
 export INST64_BASHLIB64_TARGET=''
+
+# Bootstrap
+declare DEV_BOOTSTRAP_DIR_MODE='0755'
+declare DEV_BOOTSTRAP_EXE_MODE='0755'
+declare DEV_BOOTSTRAP_PATHS='bin build docs lib src test tmp var'
+declare DEV_BOOTSTRAP_INSTALLER64_NAME='inst64'
+declare DEV_BOOTSTRAP_BASHLIB64_NAME='bl64'
+declare DEV_BOOTSTRAP_COMMAND_CURL='/usr/bin/curl'
+declare DEV_BOOTSTRAP_COMMAND_TAR='tar'
+declare DEV_BOOTSTRAP_GH_API='https://api.github.com/repos/automation64/devbin64/releases/latest'
+declare DEV_BOOTSTRAP_SOURCE='https://github.com/automation64/devbin64/releases/download'
+declare DEV_BOOTSTRAP_PACKAGE='devbin64.tar.gz'
 
 #
 # Functions
 #
+
+function dev_bootstrap_package_get_version() {
+  "$DEV_BOOTSTRAP_COMMAND_CURL" \
+    -s \
+    "$DEV_BOOTSTRAP_GH_API" |
+    grep '"tag_name":'
+}
+
+function dev_bootstrap_package_download() {
+  local package_url=''
+  local version=''
+
+  version="$(dev_bootstrap_package_get_version)" ||
+    return $?
+  version="${version##*:??}" &&
+    version="${version%%?,*}"
+  package_url="${DEV_BOOTSTRAP_SOURCE}/${version}/${DEV_BOOTSTRAP_PACKAGE}"
+  "$DEV_BOOTSTRAP_COMMAND_CURL" \
+    -s \
+    -L \
+    -o "${DEV_PATH_TMP}/${DEV_BOOTSTRAP_PACKAGE}" \
+    "$package_url"
+}
+
+function dev_bootstrap_package_open() {
+  [[ -f "${DEV_PATH_TMP}/${DEV_BOOTSTRAP_PACKAGE}" ]] &&
+    "$DEV_BOOTSTRAP_COMMAND_TAR" zx -C "$DEV_PATH_BIN" -f "${DEV_PATH_TMP}/${DEV_BOOTSTRAP_PACKAGE}" &&
+    chmod "$DEV_BOOTSTRAP_EXE_MODE" "$DEV_PATH_BIN"/* ||
+    return $?
+  rm -f "${DEV_PATH_TMP}/${DEV_BOOTSTRAP_PACKAGE}"
+  return 0
+}
+
+function dev_bootstrap_bin_populate() {
+  echo "Task: populate dev-bin (${DEV_PATH_BIN})"
+  dev_bootstrap_package_download &&
+    dev_bootstrap_package_open
+}
+
+function dev_bootstrap_lib_local_run() {
+  echo "Task: create local files (.local / .secrets)"
+  "${DEV_PATH_BIN}/dev-lib-local"
+}
+
+function dev_bootstrap_lib_base_run() {
+  echo "Task: deploy base tools (installer64 / bashlib64)"
+  "${DEV_PATH_BIN}/dev-lib-base"
+}
 
 function dev_bootstrap_dir_create() {
   echo "Task: create initial directory structure (${DEV_PATH_ROOT})"
@@ -63,8 +118,8 @@ function dev_bootstrap_dir_create() {
     return 0
   # shellcheck disable=SC2086
   mkdir \
-    --mode="$DEV_PATHS_MODE" \
-    $DEV_PATHS
+    --mode="$DEV_BOOTSTRAP_DIR_MODE" \
+    $DEV_BOOTSTRAP_PATHS
 }
 
 function dev_bootstrap_dot_env_create() {
@@ -141,7 +196,33 @@ export DEV_LIB_BASHLIB64_TARGET="${DEV_PATH_LIB}/%s"
     "$DEV_BOOTSTRAP_INSTALLER64_NAME" \
     "$DEV_BOOTSTRAP_BASHLIB64_NAME" \
     >"$DEV_BASE_ENV" &&
-    chmod "$DEV_PATHS_MODE" "$DEV_BASE_ENV"
+    chmod "$DEV_BOOTSTRAP_DIR_MODE" "$DEV_BASE_ENV"
+}
+
+function dev_bootstrap_lib_base_create() {
+  local dev_base="${DEV_PATH_BIN}/dev-lib-base"
+  echo "Task: create dev-lib-base script (${dev_base})"
+  [[ -r "$dev_base" ]] &&
+    echo 'Warning: file already create, no further action will be taken' 2>&1 &&
+    return 0
+  # shellcheck disable=SC2016
+  printf "#!/usr/bin/env bash
+#
+# Dev / Lib / Base / Install base dev-time tools
+#
+# * Use to download or install external tools, libraries, etc
+# * Tools and libs should go to lib/
+# * Customize as needed
+# * Template: 1.1.1
+#
+
+# shellcheck source=bin/dev-set
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+
+./bin/dev-lib-installer64
+" \
+    >"$dev_base" &&
+    chmod "$DEV_BOOTSTRAP_EXE_MODE" "$dev_base"
 }
 
 function dev_bootstrap_dot_local_create() {
@@ -166,7 +247,7 @@ function dev_bootstrap_dot_local_create() {
 export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
 ' \
     >"$DEV_BASE_DOT_LOCAL" &&
-    chmod "$DEV_PATHS_MODE" "$DEV_BASE_DOT_LOCAL"
+    chmod "$DEV_BOOTSTRAP_DIR_MODE" "$DEV_BASE_DOT_LOCAL"
 }
 
 function dev_bootstrap_dot_secrets_create() {
@@ -187,7 +268,7 @@ function dev_bootstrap_dot_secrets_create() {
 #
 ' \
     >"$DEV_BASE_DOT_SECRETS" &&
-    chmod "$DEV_PATHS_MODE" "$DEV_BASE_DOT_SECRETS"
+    chmod "$DEV_BOOTSTRAP_DIR_MODE" "$DEV_BASE_DOT_SECRETS"
 }
 
 function dev_bootstrap_gitignore_create() {
@@ -196,9 +277,7 @@ function dev_bootstrap_gitignore_create() {
     echo 'Warning: file already create, no further action will be taken' 2>&1 &&
     return 0
   # shellcheck disable=SC2016
-  printf '
-
-#
+  printf '#
 # GIT Ignore
 #
 # * Template version: 1.2.1
@@ -214,7 +293,7 @@ function dev_bootstrap_gitignore_create() {
 /lib/*
 
 # Dev-time temporary files
-/tmp/*
+${DEV_PATH_TMP}/*
 
 # Secrets
 /.secrets
@@ -242,42 +321,6 @@ function dev_bootstrap_dot_env_load() {
   source "$DEV_BASE_ENV"
 }
 
-function dev_bootstrap_installer64_get_version() {
-  local api_latest="https://api.github.com/repos/${DEV_LIB_INSTALLER64_OWNER}/releases/latest"
-  curl \
-    -s \
-    "$api_latest" |
-    awk -F: '/"tag_name":/ { gsub( /[ ,"]/,"" ); print $2}'
-}
-
-function dev_bootstrap_installer64_get() {
-  local version=''
-  local package_url=''
-  version="$(dev_bootstrap_installer64_get_version)" &&
-    package_url="https://github.com/${DEV_LIB_INSTALLER64_OWNER}/releases/download/${version}/install-installer64" ||
-    return $?
-  curl \
-    --remote-name \
-    --location \
-    "$package_url"
-}
-
-function dev_bootstrap_installer64_deploy() {
-  local -i status=1
-  echo "Task: deploy dev-tool (Installer64)"
-  [[ -d "$DEV_LIB_INSTALLER64_TARGET" ]] &&
-    echo 'Warning: tool already installed, no further action will be taken' 2>&1 &&
-    return 0
-
-  dev_bootstrap_installer64_get "$version" ||
-    return $?
-
-  bash ./install-installer64
-  status=$?
-  rm -f ./install-installer64
-  return $status
-}
-
 function dev_bootstrap_initializer() {
   # Initialize .env variables for the bootstrap process
   DEV_PATH_ROOT="$(pwd)"
@@ -286,7 +329,7 @@ function dev_bootstrap_initializer() {
   DEV_LIB_INSTALLER64_TARGET="${DEV_PATH_LIB}/${DEV_BOOTSTRAP_INSTALLER64_NAME}"
 
   # Initialize Installer64 parameters
-  INST64_INSTALLER64_TARGET="$DEV_LIB_INSTALLER64_TARGET"
+  DEV_PATH_BIN="$DEV_LIB_INSTALLER64_TARGET"
   INST64_BASHLIB64_TARGET="$DEV_LIB_BASHLIB64_TARGET"
 }
 
@@ -307,7 +350,10 @@ dev_bootstrap_initializer &&
   dev_bootstrap_dot_secrets_create &&
   dev_bootstrap_dot_env_load &&
   dev_bootstrap_gitignore_create &&
-  dev_bootstrap_installer64_deploy
+  dev_bootstrap_bin_populate &&
+  dev_bootstrap_lib_base_create &&
+  dev_bootstrap_lib_local_run &&
+  dev_bootstrap_lib_base_run
 dev_bootstrap_status=$?
 
 if ((dev_bootstrap_status == 0)); then
